### ISSUE TITLE
Bad Error Description shortcut in README (Inspect)

### ISSUE THREAD

**Issue by ouattararomuald** [dmimat/intellij-mnemonic-keymap#1]
I installed the plugin and noticed that the shortcut for error description is: `Cmd+I, D` as opposed to the current README `Cmd+I, E`.

I use an AZERTY keyboard.

**Comment by dmimat** [comment]
Thanks for noticing!
The correct shortcut is `Cmd/Ctrl+I, E`. The problem was only in the macOS keymap. it is fixed in version 2023.1.0
