### ISSUE TITLE
Mnemonic Keymap PDF Cheatsheet

### ISSUE THREAD

**Issue by smotron** [dmimat/intellij-mnemonic-keymap#10]
Could you provide the Mnemonic Keymap cheatsheet in a PDF format for download? The current version available here:

https://plugins.jetbrains.com/plugin/19094-mnemonic-keymap

is helpful, but unfortunately, it is a low-resolution JPG, making it unsuitable for printing.

**Comment by dmimat** [comment]
The list of shortcuts in the keymap differs depending on the IDE you are using.
To get a PDF with the actual list of shortcuts in your IDE, please use the Keymap Exporter plugin:
https://plugins.jetbrains.com/plugin/7066-keymap-exporter
