### ISSUE TITLE
Support for Rust Rover

### ISSUE THREAD

**Issue by neugartf** [dmimat/intellij-mnemonic-keymap#11]
For some reason the keymap doesnt seem to be supported by RustRover (yet). 
What are the necessary changes? 
https://plugins.jetbrains.com/plugin/19094-mnemonic-keymap/versions

**Comment by dmimat** [comment]
The problem is fixed. Mnemonic keymap is now available in RustRover:

![image](https://github.com/user-attachments/assets/a62579bd-5199-4a0f-b20e-8435282bbcfd)

**Comment by dmimat** [comment]
@neugartf , BTW if you know of some RustRover-specific actions that are not handled by this keymap, please let me know.
