### ISSUE TITLE
Feature Request: keybinding for `Open Source in new window `

### ISSUE THREAD

**Issue by hab25** [dmimat/intellij-mnemonic-keymap#3]
There are no bindings for creating new views, like  `Other/Open source in window` or `Main Menu/Window/Editor Tabs/Split Right`.

I have a preference for `Other/Open source in window` because I use a window manager and like to have the same split management keybindings across all my applications.

**Comment by dmimat** [comment]
Thanks for the feedback!
I added the following shortcuts:
- Open Source in New Window (`Cmd/Ctrl+E, N`)
- Move Tab to Right/Down Split (`Cmd/Ctrl+E, 5/6`)
