### ISSUE TITLE
Proposal: Add hotkey for `Annotate` action

### ISSUE THREAD

**Issue by osipxd** [dmimat/intellij-mnemonic-keymap#7]
Just sharing the hotkey I've added for "Annotate" action in case anyone else want to use it.

**Action group:**  VCS actions (<kbd>Ctrl</kbd>+<kbd>K</kbd>)
**Mnemonics candidates:**
❌ <kbd>A</kbd> - `annotate` (occupied by "Add to VCS" action)
❌ <kbd>B</kbd> - `blame` (occupied by "Branches" action)
✅ <kbd>W</kbd> - `who`

**Comment by azolotko** [comment]
Another alternative: `Y` - `why?`
